server:
  port: 9000

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
      bindings:
        greetings-in:
          destination: greetings
          contentType: application/json
        greetings-out:
          destination: greetings
          contentType: application/json
        item-in:
          destination: item
          contentType: application/json
        item-out:
          destination: item
          contentType: application/json
        